{{- $virtualServiceName := "virtualservice" -}}
{{- $gateways := .Values.gateways }}
{{- $hosts := .Values.hosts }}
{{- $headers := .Values.headers }}
{{- range .Values.virtualservices }}
{{- $namespace := .namespace }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: {{ $namespace }}
  name: {{ $virtualServiceName }}-{{ $namespace }}
spec:
  hosts:
    {{- range $hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    {{- range $gateways }}
    - {{ . | quote }}
    {{- end }}
  http:
    {{- range .paths }}
    - match:
        - uri:
            prefix: {{ .path }}
      {{- if .rewrite_url }}
      rewrite:
        uri: {{ .rewrite_url }}
      {{- end }}
      route:
        - destination:
            port:
              number: {{ .servicePort }}
            host: {{ .serviceName }}.{{ $namespace }}.svc.cluster.local
      timeout: {{ .timeout | default "30s" }}
      {{- if $headers }}
      headers:
        {{- if .headers }}
          {{- merge .headers $headers  | toYaml | nindent 8 }}
        {{- else }}
          {{- $headers | toYaml | nindent 8 }}
        {{- end }}
      {{- else if .headers }}
      headers:
        {{- .headers | toYaml | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
