apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tang-spring-helm.fullname" .}}
  labels:
    {{- include "tang-spring-helm.labels" . | nindent 4 }}
data:
  application-{{ .Values.environment }}.yaml: |-
  {{- if .Values.configmap }}
  {{- .Values.configmap | nindent 4 }}
  {{- end }}
