apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tang-spring-helm.fullname" .}}
  labels:
    {{- include "tang-spring-helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tang-spring-helm.fullname" .}}
subjects:
  - kind: ServiceAccount
    name: {{ include "tang-spring-helm.serviceAccountName" .}}
