apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tang-spring-helm.fullname" .}}
  labels:
    {{- include "tang-spring-helm.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - pods
    verbs:
      - get
      - watch
      - list
