{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tang-spring-helm.serviceAccountName" .}}
  labels:
  {{- include "tang-spring-helm.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.managedIdentity.enabled }}
    azure.workload.identity/client-id: {{ .Values.managedIdentity.clientId }}
    {{- end }}
  {{- end }}
