apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tang-secret-provider
  namespace: maybetang
spec:
  parameters:
    clientID: 57bdf346-443d-4db0-b074-ec598a5f5a85
    keyvaultName: enablement-app-kv-nonprd
    objects: |
      array:
        - |
          objectName: sap-username-dev
          objectType: secret
        - |
          objectName: sap-password-dev
          objectType: secret
    resourceGroup: Rg-Enablement-App-USSC-NonProd
    subscriptionId: efede11f-18f5-4297-ac13-1e4582c232ff
    tenantId: d1ee1acd-bc7a-4bc4-a787-938c49a83906
    usePodIdentity: 'false'
  provider: azure
  secretObjects:
    - data:
        - key: sap.service.username
          objectName: sap-username-dev
        - key: sap.service.password
          objectName: sap-password-dev
      secretName: tang-secret
      type: Opaque
